apps/login_registration/urls.py
from django.conf.urls import url, include
from . import views

def test(request):
    print "*********************"

urlpatterns = [
    url(r'^$', views.index, name = "index"),
    url(r'^register$', views.register),
    url(r'^login$', views.login),
]

apps/secrets/urls.py
from django.conf.urls import url
from . import views

def test(request):
    print "*********************"

urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url(r'^create$', views.create, name = 'create'),
    url(r'^delete_secret$', views.delete_secret, name = 'delete_secret'),
    url(r'^like_secret$', views.like_secret, name = 'like_secret'),
    url(r'^logout$', views.logout, name = 'logout'),
]

dojo_secrets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

def test(request):
    print "*********************"

urlpatterns = [
    url(r'^', include("apps.login_registration.urls", namespace = 'login_registration')),
    url(r'^secrets', include("apps.secrets.urls", namespace = "secrets")),
]

apps/login_registration/models.py
from __future__ import unicode_literals

from django.db import models
import re, bcrypt

EMAIL_REGEX = re.compile(r"^[^@\s]+@[^@\s]+.[^@\s]+$")
NAME_REGEX = re.compile(r'^[a-zA-Z]+$')

class UserManager(models.Manager):
    def validate_and_register(self, postData):
        errors = {}
        
        # First Name Validation
        if not len(postData['first_name']):
            errors['first_name'] = "First name field can not be empty."
        elif  not re.match(NAME_REGEX, postData['first_name']):
            errors['first_name'] = "Invalid first name! Please input only letter characters."
        elif len(postData['first_name']) < 2:
            errors['first_name'] = "First name too short."
        
        # Last name Vlaidation
        if not len(postData['last_name']):
            errors['last_name'] = "Last name field can not be empty."
        elif  not re.match(NAME_REGEX, postData['last_name']):
            errors['last_name'] = "Invalid last name! Please input only letter characters."
        elif len(postData['last_name']) < 2:
            errors['last_name'] = "Last name too short."
        
        # Email Validation
        if not len(postData['email']):
            errors['email'] = "Email field can not be empty."
        elif not re.match(EMAIL_REGEX, postData['email']):
            errors['email'] = "Invalid email! Please input the right format of an email like: user@mail.com"
        elif self.filter(email = postData['email']):
            errors['email'] = "Error! Email already in use."
        
        # Password Validation
        if not len(postData['password']):
            errors['password'] = "Password field can not be empty."
        elif len(postData['password']) < 8:
            errors['password'] = "Password too short. Input at least 8 characters"
        elif postData['password'] != postData['confirm_pass']:
            errors['confirm_pass'] = "Password not confirmed. Please pay more attention"
       
        # Return of the validation results for register method
        if len(errors):
            return (False, errors)
        else:
            password = postData['password'].encode()
            hashed = bcrypt.hashpw(password, bcrypt.gensalt())
            print hashed, "************#############____________________---------++++++++++==========="
            print len(hashed)
            self.create(first_name = postData['first_name'], last_name = postData['last_name'], email = postData['email'], password = hashed)
            return (True, postData['first_name'])

    def validate_and_login(self, postData):
        errors_login = {}
        # Email Validation when Login
        if not len(postData['email']):
            errors_login['login_email_error'] = "Please provide an email."
        else:
            if not self.filter(email = postData['email']):
                errors_login['login_error'] = "Email or password wrong."
        
        if not len(errors_login):
            user = self.filter(email = postData['email'])
        # # Password Validation when Login
            if not len(postData['password']):
                errors_login['login_password_error'] = "Please provide password."
            else:
                password = postData['password'].encode()
                hashed = self.filter(email = postData['email'])[0].password.encode()
                if not bcrypt.checkpw(password, hashed):
                    errors_login['login_error'] = "Email or password wrong."
                    print  "(((((((()))))))))))^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"

        
        # Return of the validation results for login method
        if len(errors_login):
            return (False, errors_login)
        else:
            return (True, self.filter(email = postData['email']))





class User(models.Model):
    first_name = models.CharField(max_length = 255)
    last_name = models.CharField(max_length = 255)
    email = models.CharField(max_length = 255)
    password = models.CharField(max_length = 255)
    objects = UserManager()

# Create your models here.

apps/secrets/models.py
from __future__ import unicode_literals

from django.db import models
from ..login_registration.models import User
from django.db.models import Count

class SecretManager(models.Manager):
    def create_secret(self, postData, user_id):
        secret = self.create(content = postData['the_secret'], creator = User.objects.get(id = user_id))
        return secret

    def add_like(self, postData):
        the_user = User.objects.get(id = postData['user_id'])
        the_secret = Secret.objects.get(id = postData['secret_id'])
        the_secret.like.add(the_user)
        likes_count = Secret.objects.annotate(num_likes = Count('like'))
        return likes_count

class Secret(models.Model):
    content = models.TextField(max_length = 500)
    created_at = models.DateTimeField(auto_now_add = True)
    update_at = models.DateTimeField(auto_now = True)
    creator = models.ForeignKey(User, related_name = "creator", null = True)
    like = models.ManyToManyField(User, related_name = "liked")

    objects = SecretManager()

# Create your models here.

apps/login_registration/views.py
from django.shortcuts import render, redirect
from .models import User

def index(request):
    return render(request, "login_registration/index.html")

def register(request):
    result = User.objects.validate_and_register(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "login_registration/index.html", context)
    if result[0] == True:
        context = {
            'user_name': result[1],
            'action': "successfully registered!"
        }
        return render(request, "login_registration/index.html", context)

def login(request):
    result = User.objects.validate_and_login(request.POST)
    if result[0] == False:
        context = {
            'result':result[1]
        }
        return render(request, "login_registration/index.html", context)
    if result[0] == True:
        request.session['user_name'] = result[1][0].first_name
        request.session['user_id'] = result[1][0].id
        return redirect('/secrets')

# Create your views here.

apps/secrets/views.py
from django.shortcuts import render, redirect
# from .models import Secret
from .models import Secret
from ..login_registration.models import User
from django.db.models import Count
from django.contrib import messages

def index(request):
    if not "user_name" in request.session:
        messages.add_message(request, messages.INFO, "Must be logged in to view this page")
        return redirect('login_registration:index')
    context = {
        'secrets': Secret.objects.annotate(num_likes = Count('like')).order_by('-created_at')[:5],
        'logged_user': User.objects.get(id = request.session['user_id'])
    }
    return render(request, "secrets/secrets.html", context)

def create(request):
    if request.method == 'POST':
        secret = Secret.objects.create_secret(request.POST, request.session['user_id'])
        return redirect('secrets:index')

def delete_secret(request):
    if request.method == 'POST':
        Secret.objects.get(id = request.POST['secret_id']).delete()
        return redirect('secrets:index')

def like_secret(request):
    if request.method == 'POST':
        like = Secret.objects.add_like(request.POST)
        return redirect('secrets:index')

def logout(request):
    request.session.clear()
    return redirect('login_registration:index')



# Create your views here.

apps/login_registration/templates/login_registration/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login and Register | Home</title>
    <style>
    #error{
        color: red;
    }
    #success{
        color: green;
    }
    </style>
</head>
<body>
    <h1>Registration</h1>
    <form action="register" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="first_name">First Name:</label></td>
                <td><input type="text" name="first_name"></td>
                <td id="error">{{result.first_name}}</td>
            </tr>
            <tr>
                <td><label for="last_name">Last Name:</label></td>
                <td><input type="text" name="last_name"></td>
                <td id="error">{{result.last_name}}</td>
            </tr>
            <tr>
                <td><label for="email">Email:</label></td>
                <td><input type="email" name="email"></td>
                <td id="error">{{result.email}}</td>
            </tr>
            <tr>
                <td><label for="password">Password:</label></td>
                <td><input type="password" name="password"></td>
                <td id="error">{{result.password}}</td>
            </tr>
            <tr>
                <td><label for="confirm_pass">Confirm password:</label></td>
                <td><input type="password" name="confirm_pass"></td>
                <td id="error">{{result.confirm_pass}}</td>
            </tr>
        </table>
        <br>
        <input type="submit" value="Register">
    </form>
    <br>
    <h1>Login</h1>

    {% for message in messages %}
        <h3>{{message}}</h3>
    {% endfor %}

    <form action="login" method="post">
        {% csrf_token %}
        <table>
            <tr>
                <td><label for="email">Email:</label></td>
                <td><input type="email" name="email"></td>
                <td id="error">{{result.login_email_error}}</td>
            </tr>
            <tr>
                <td><label for="password">Password:</label></td>
                <td><input type="password" name="password"></td>
                <td id="error">{{result.login_password_error}}</td>
            </tr>
        </table>
        <br>
        <p id="error">{{result.login_error}}</p>
        <br>
        <input type="submit" value="Login">
    </form>
    <h3 id="success">{{user_name}} {{action}}</h3>
</body>
</html>

apps/secrets/templates/secrets/secrets.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dojo Secrets</title>
</head>
<body>
    <h1>Hello, {{request.session.user_name}}!</h1>

    <form action="{% url 'secrets:logout' %}" method="post">
        {% csrf_token %}
        <input type="submit", value="Logout">
    </form>
    <br>

    <form action="{% url 'secrets:create' %}" method="post">
        {% csrf_token %}
        <textarea name="the_secret" id="" cols="60" rows="10" placeholder="Your secret here..."></textarea><br><br>
        <input type="submit" value="POST">
    </form>
    <br>
    <a href="popular_secrets">Most Popular Secrets</a>
    <h1>Recent Secrets...</h1>


    {% for secret in secrets %}
        <h3>{{secret.content}}<h3>
        <p><i>({{secret.created_at|timesince}} ago)</i></p>

        {% if secret.creator == logged_user %}
            <form action="{% url 'secrets:delete_secret' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="secret_id" value="{{secret.id}}">
                <input type="submit" value="Delete">
            </form>
        {% endif %}

        {% if logged_user not in secret.like.all %}
            <form action="{% url 'secrets:like_secret' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="user_id" value="{{request.session.user_id}}">
                <input type="hidden" name="secret_id" value="{{secret.id}}">
                <input type="submit" value="Like">
            </form>
        {% else %}
            <i> You liked this!</i>
        {% endif %}

    {% endfor %}


</body>
</html>